### ISSUE TITLE
NoMethodError - undefined method `end_with?' for nil:NilClass

### ISSUE THREAD

**Issue by andrewspear** [jesalg/commit-hawk#5]
Hi there, I just tried setting up this app in Heroku but it gives an Internal Server Error whenever the Github webhook is triggered. Looking into the log files it the culprit appears to be `NoMethodError - undefined method 'end_with?' for nil:NilClass` which comes from `server.rb`. I have not modified any of the commit-hawk files, this is an exact clone of the current version.

Here's the full stack trace:

```
2020-08-12T05:17:08.832271+00:00 heroku[router]: at=info method=POST path="/payload?branch=master&watching=readme.md" host=commits-to-slack.herokuapp.com request_id=39f68bcb-9218-41e2-83f9-19cf9e705cda fwd="140.82.115.151" dyno=web.1 connect=1ms service=11ms status=500 bytes=255 protocol=https
2020-08-12T05:17:08.824945+00:00 app[web.1]: 2020-08-12 05:17:08 - NoMethodError - undefined method `end_with?' for nil:NilClass:
2020-08-12T05:17:08.824955+00:00 app[web.1]: 	/app/server.rb:31:in `watched_changes'
2020-08-12T05:17:08.824956+00:00 app[web.1]: 	/app/server.rb:20:in `block in <top (required)>'
2020-08-12T05:17:08.824957+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `call'
2020-08-12T05:17:08.824958+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!'
2020-08-12T05:17:08.824958+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
2020-08-12T05:17:08.824958+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'
2020-08-12T05:17:08.824959+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
2020-08-12T05:17:08.824959+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'
2020-08-12T05:17:08.824959+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `catch'
2020-08-12T05:17:08.824960+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'
2020-08-12T05:17:08.824960+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'
2020-08-12T05:17:08.824961+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `each'
2020-08-12T05:17:08.824961+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'
2020-08-12T05:17:08.824961+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'
2020-08-12T05:17:08.824962+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
2020-08-12T05:17:08.824962+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
2020-08-12T05:17:08.824962+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
2020-08-12T05:17:08.824963+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'
2020-08-12T05:17:08.824963+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'
2020-08-12T05:17:08.824964+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
2020-08-12T05:17:08.824964+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
2020-08-12T05:17:08.824964+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
2020-08-12T05:17:08.824965+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'
2020-08-12T05:17:08.824965+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'
2020-08-12T05:17:08.824965+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'
2020-08-12T05:17:08.824966+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'
2020-08-12T05:17:08.824966+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'
2020-08-12T05:17:08.824966+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
2020-08-12T05:17:08.824966+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
2020-08-12T05:17:08.824967+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'
2020-08-12T05:17:08.824968+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/logger.rb:17:in `call'
2020-08-12T05:17:08.824968+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
2020-08-12T05:17:08.824968+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:231:in `call'
2020-08-12T05:17:08.824969+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:224:in `call'
2020-08-12T05:17:08.824969+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
2020-08-12T05:17:08.824969+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
2020-08-12T05:17:08.824969+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'
2020-08-12T05:17:08.824970+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'
2020-08-12T05:17:08.824970+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `block in call'
2020-08-12T05:17:08.824971+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1729:in `synchronize'
2020-08-12T05:17:08.824971+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `call'
2020-08-12T05:17:08.824971+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
2020-08-12T05:17:08.824972+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
2020-08-12T05:17:08.824972+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
2020-08-12T05:17:08.824984+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
2020-08-12T05:17:08.824985+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
2020-08-12T05:17:08.824985+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
2020-08-12T05:17:08.824985+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
2020-08-12T05:17:08.824986+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
2020-08-12T05:17:08.824986+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
2020-08-12T05:17:08.824986+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
2020-08-12T05:17:08.824987+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
2020-08-12T05:17:08.824987+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
2020-08-12T05:17:08.824988+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
2020-08-12T05:17:08.824988+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/bin/thin:23:in `load'
2020-08-12T05:17:08.824988+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/bin/thin:23:in `<top (required)>'
2020-08-12T05:17:08.824989+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
2020-08-12T05:17:08.824989+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
2020-08-12T05:17:08.824989+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
2020-08-12T05:17:08.824989+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
2020-08-12T05:17:08.824990+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2020-08-12T05:17:08.824991+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2020-08-12T05:17:08.824991+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
2020-08-12T05:17:08.824991+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
2020-08-12T05:17:08.824992+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
2020-08-12T05:17:08.824992+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
2020-08-12T05:17:08.824992+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
2020-08-12T05:17:08.824992+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
2020-08-12T05:17:08.824993+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
2020-08-12T05:17:08.824993+00:00 app[web.1]: 	/app/vendor/bundle/bin/bundle:104:in `load'
2020-08-12T05:17:08.824993+00:00 app[web.1]: 	/app/vendor/bundle/bin/bundle:104:in `<main>'
2020-08-12T05:17:08.825248+00:00 app[web.1]: 140.82.115.151 - - [12/Aug/2020:05:17:08 +0000] "POST /payload?branch=master&watching=readme.md HTTP/1.1" 500 30 0.0021
```

Any ideas?

**Comment by jesalg** [comment]
@andrewspear Thanks for the bug report. What does your Settings -> Webhook URL look like in GitHub?

**Comment by andrewspear** [comment]
False alarm I think. The errors only come when Github fires it's tests, when I made a real push it worked fine:

<img width="443" alt="0T0mtNLJlPJapnAV" src="https://user-images.githubusercontent.com/1787336/90077978-96326600-dd57-11ea-9d46-fca0e9cef603.png">

Perhaps the payload is slightly different when they do their test calls 🤷‍♀️

At any rate, real use cases are running fine now thanks.

**Comment by jesalg** [comment]
Ah, interesting. Good to know!
